### PR TITLE
[SPEC] Adjust Concat to specification

### PR DESCRIPTION
**Pull request by mbencer**
According to specification `m_concatenation_axis` should be changed to `m_axis`.

### CODE REVIEW

**Comment by jbobba** [comment]
@mbencer @postrational why isn't this change creating v1::concat?

**Comment by mbencer** [comment]
> @mbencer @postrational why isn't this change creating v1::concat?

@jbobba 
I've considered such solution for `Concat` but the only change is changing `m_concatenation_axis` by `m_axis`. In such case we have to copy almost all `Concat` code without any changes.
On the other hand as @diyessi mentioned solution without introduction `v1` forces change of other transformers which use `Concat`.

Probably the compromise can be introduction `Concat:v1` which inherits from `Concat:v0` and only override `m_concatenation_axis` - I prepared draft of such solution: https://github.com/NervanaSystems/ngraph/pull/3616/files
@postrational @diyessi @jbobba What do you think about it?

**Comment by postrational** [comment]
I think we can simplify this PR by leaving `get_concatenation_axis` as an alias for `get_axis`.

**Comment by mbencer** [comment]
> I think we can simplify this PR by leaving `get_concatenation_axis` as an alias for `get_axis`.

For me it is good idea ;) It is worth to emphasize that during serialization `axis` name is used - so it seems to be consistent. I implemented the change.

**Comment by mbencer** [comment]
@aslepko, @indie, @silee2 and @wenzhe-nrv were added as reviewers by incorrect commits, so I removed them from review ;)

**Pull request merged**
