### PR TITLE
ScatterAdd and ScatterUpdate ops

### PR DESCRIPTION
**Pull request by arogowie-intel**
This PR is build on top of: #4438

### CODE REVIEW

**Comment by arogowie-intel** [comment]
Sorry for mess in git history. Please take a look only on files related to `scatter_update.xpp`, `scatter_add.xpp` and  tests in `type_prop\scatter_update.cpp` `type_prop\scatter_add.cpp`.

**Comment by raramer01** [comment]
TESTNOW_DLDT_E2E

**Comment by raramer01** [comment]
TESTNOW

**Comment by arogowie-intel** [comment]
I'm closing this PR since it doesn't have to be build on top of #4438 and because of merging artifacts.

**Comment by arogowie-intel** [comment]
New version is here #4518

**Pull request closed without merging**
