### PR TITLE
A reference implementation of batchnorm fprop and tests.

### PR DESCRIPTION
**Pull request by varun-intel**
-> Implements batchnorm fprop in the interpreter backends and adds a couple tests to verify that it is correct.
-> We need the interpreter implementation to run our nnp tests through the NNP_TESTER class, which compares against the interpreter.
-> Bprop to be added in another pr.

### CODE REVIEW

**Comment by varun-intel** [comment]
TESTNOW

**Comment by varun-intel** [comment]
TESTNOW

**Comment by aprocter** [comment]
TESTNOW

**Comment by aprocter** [comment]
TESTNOW

**Pull request merged**
