### PR TITLE
Replace relu implementation with element_wise

### PR DESCRIPTION
**Pull request by silee2**
Relu is removed from recent version of mkl-dnn.

### CODE REVIEW

**Comment by silee2** [comment]
PaddlePaddle relies on externally built mkl-dnn and the whole #2284 is not needed to fix compilation issues. Can we merge this PR into master if it does not break anything? We would need to switch relu implementation when we upgrade mkl-dnn anyway.

**Comment by silee2** [comment]
@mbrookhart Is this new implementation compatible with the mkl-dnn version that Amazon uses?

**Comment by baojun-nervana** [comment]
@avijit-nervana @diyessi

**Comment by mbrookhart** [comment]
@jbobba is out, remove him from the reviewers?

**Pull request merged**
