### PR TITLE
BatchNorm documentation

### PR DESCRIPTION
**Pull request by diyessi**

### CODE REVIEW

**Comment by diyessi** [comment]
There are a lot of things I don't like about this BatchNorm op. Now there are more.

**Comment by mbrookhart** [comment]
This is an example of what we're currently doing in the bridge to work around this: https://github.com/NervanaSystems/ngraph-mxnet/pull/207

**Comment by DawnStone** [comment]
TESTNOW

**Comment by diyessi** [comment]
I've changed this to what I think we want BatchNorm to be.

**Pull request merged**
