### PR TITLE
Update includes in reference runtime headers

### PR DESCRIPTION
**Pull request by pavel-rodionov**
Include additional headers to reference runtime files to make them self-sufficient

### CODE REVIEW

**Comment by raramer01** [comment]
TESTNOW_DLDT_E2E

**Comment by raramer01** [comment]
TESTNOW_DLDT_E2E

**Comment by rkimballn1** [comment]
It was failing style check so I fixed it. Hope you don't mind.

**Comment by rkimballn1** [comment]
@diyessi I agree that a test would be great but I think that is beyond the scope of this PR. Perhaps a separate PR?

**Comment by pavel-rodionov** [comment]
Can we merge this MR as is and then in few days I will create another MR with proposed test?

**Comment by diyessi** [comment]
Certainly, once @GlebKazantaev has reviewed.

**Pull request merged**
