### PR TITLE
Added the capability of directly compiling cuda and ptx to CMake.

### PR DESCRIPTION
**Pull request by csullivan**
With these CMAKE changes we add support for compiling CUDA with NVCC. This compliments the current RT compilation via NVRTC.

### CODE REVIEW

**Comment by csullivan** [comment]
TESTNOW

**Comment by csullivan** [comment]
I have done so successfully with my local install of gcc. Not sure about clang. I will try it with clang and report back.

**Comment by csullivan** [comment]
Good catch, clang-GPU hits the following error:
```
nvcc fatal   : The version ('30901') of the host compiler ('clang') is not supported

```

**Comment by fengleitian** [comment]
I see somewhere clang is going to support it. but not sure which version.

**Comment by csullivan** [comment]
PR #1009 adds CUDA 9.1 support while retaining backward compatibility with CUDA 8. Once the CI and dev nodes are upgraded, we can merge this in.

**Comment by csullivan** [comment]
Finally resurrecting this one to support direct NVCC compilation.

**Comment by csullivan** [comment]
Failing CI due to `-Wreserved-id-macro` conflict with `cuda_runtime.h`
```
In file included from <built-in>:1:
/usr/local/cuda/include/cuda_runtime.h:51:9: error: macro name is a reserved identifier [-Werror,-Wreserved-id-macro]
#define __CUDA_RUNTIME_H__
        ^
```

**Pull request merged**
