### PR TITLE
Remove XLA compatibility fig leaves

### PR DESCRIPTION
**Pull request by aprocter**
Marking WIP because we haven't yet adapted `ngraph-tensorflow-1.3`.

### CODE REVIEW

**Comment by Krovatkin** [comment]
@diyessi @aprocter 
I was wondering if we might want to repurpose an `XLATuple` into a `Tuple` which we could use for multi-output ops in autodiff? Unless you guys already decided how we are going to support `generate_adjoints` for multi-output ops?

**Comment by diyessi** [comment]
No needed for that.

**Comment by aprocter** [comment]
Removing WIP because we have a PR ready to deal with this in ngtf-1.3 now.

**Comment by adstraw** [comment]
@diyessi can you review today?

**Pull request merged**
