### PR TITLE
Bug fix for invalid memory access to Constant (GPU backend)

### PR DESCRIPTION
**Pull request by xiezhq-hermann**
Fix the incorrect way to query the size of Constant tensor, which lead invalid memory access

### CODE REVIEW

**Comment by xiezhq-hermann** [comment]
Check this issue for the details of this PR: https://github.com/NervanaSystems/ngraph/issues

**Comment by xiezhq-hermann** [comment]
Hi, could you please reveal the reason for not pass the checks?

**Comment by rkimballn1** [comment]
@xiezhq-hermann your PR has been merged in as PR @2162. Thank you for finding and fixing this bug. Your support is appreciated.

**Comment by rkimballn1** [comment]
Our merge procedure is faulty and @xiezhq-hermann did not get the credit for the fix. I am reopening so we can get this done right. Sorry for the inconvenience

**Pull request merged**
