### PR TITLE
add enable gpu convolution tests flag in py

### PR DESCRIPTION
**Pull request by fengleitian**

### CODE REVIEW

**Comment by fengleitian** [comment]
@rkimballn1 good point, let me change it.

**Comment by fengleitian** [comment]
updated with a skip list, just add the backend name that need to skip in the list. it will create a string to skip the test.

**Comment by fengleitian** [comment]
@diyessi add a flag to make comments.
`"TODO: Need to implement this op for GPU later;"`

**Comment by rkimballn1** [comment]
TESTNOW

**Pull request merged**
