### PR TITLE
NNP test include refactoring [needs this in NNP repo]

### PR DESCRIPTION
**Pull request by yxlao**
Also in https://github.com/NervanaSystems/nnp-transformer/pull/11

### CODE REVIEW

**Comment by yxlao** [comment]
TESTNOW

**Comment by DawnStone** [comment]
TESTNOW

**Comment by DawnStone** [comment]
TESTNOW

**Comment by DawnStone** [comment]
TESTNOW

**Comment by yxlao** [comment]
TESTNOW

**Pull request merged**
