### PR TITLE
Added additional check to v1 reshape op

### PR DESCRIPTION
**Pull request by ilyachur**

### CODE REVIEW

**Comment by raramer01** [comment]
TESTNOW_DLDT_E2E

**Comment by raramer01** [comment]
TESTNOW_DLDT_E2E

**Comment by raramer01** [comment]
TESTNOW_DLDT_E2E

**Comment by jane-intel** [comment]
We already have such check. Please close current PR

https://github.com/NervanaSystems/ngraph/blob/master/src/ngraph/op/reshape.cpp#L202

**Comment by jane-intel** [comment]
Check is in master. Closing

**Pull request closed without merging**
