### PR TITLE
Make apply-code-format set correct permissions on source files

### PR DESCRIPTION
**Pull request by Krovatkin**

### CODE REVIEW

**Comment by postrational** [comment]
Good idea. We could also add something to change line endings to Unix LF.

**Comment by Krovatkin** [comment]
@postrational I could definitely add that. Let's see what @diyessi and @rkimballn1 think.

**Comment by Krovatkin** [comment]
@diyessi they are being set too permissively if a file is edited on windows over a samba share which is a really really really convenient way to edit files 😄

**Comment by diyessi** [comment]
Then you could just set umask in the script so everything get created less permissively.

**Comment by Krovatkin** [comment]
@diyessi `umask` **seems** to work to my surprise (because every new session still shows the old `umask` 🤷‍♂️ ) but it needs to be set before any files are edited or created which is a relatively big caveat. Let alone the fact that some users might **not** appreciate our scripts modifying their `umask` setting even if it is only for the current session. I find setting using `chmod 0644` is a way more reliable and direct way to achieve what we want 😄

**Comment by diyessi** [comment]
umask should only affect what happens in the script since it's a separate process.

**Comment by aprocter** [comment]
Should we update check-code-format as well? (Mispermissioned files would block CI in that case, not sure how we feel about that).

**Comment by Krovatkin** [comment]
@aprocter I don't know either. This is kinda the best effort w/o over-imposing.

**Pull request merged**
