### PR TITLE
ConvolutionRelu

### PR DESCRIPTION
**Pull request by Krovatkin**

### CODE REVIEW

**Comment by Krovatkin** [comment]
Interestingly enough, it fails the new test I added when compiled w/ GCC. I'll investigate tomorrow.

**Comment by Krovatkin** [comment]
@jbobba could you please take a look when you have a moment? I think it's semi-ready and should be passing CI

**Comment by adstraw** [comment]
please fix merge conflict

**Comment by Krovatkin** [comment]
@jbobba 

> Dont we need more checks to see if the Convolution is supported by MKLDNN before fusing it to ConvolutionRelu?

We talked about it a few days ago. Basically, I was asking if I need to do any checks in `CPUFusion` and you seem to have indicated that we can always fuse :-)

@adstraw will do shortly

**Comment by Krovatkin** [comment]
@jbobba I added the checks from `CPUAssignment` pass. Please let me know if those are good enough? 
@adstraw alright, resolved the merge conflicts.

**Comment by adstraw** [comment]
"Can you also add a comment to cpu fusion as to why we are checking for these specific attributes or pull that code out into a utility function" <- this needs to get done pre-merge, yes?

**Comment by Krovatkin** [comment]
@jbobba @adstraw done.

**Comment by Krovatkin** [comment]
> LGTM, this include the forward part, is the backprop part in a separate PR?

My understanding was we weren't doing backprop atm? @jbobba ?

**Comment by jbobba** [comment]
Right, backprop should be a different PR.

**Pull request merged**
