### PR TITLE
Change the call frame order in pybind wrapper tests

### PR DESCRIPTION
**Pull request by nbpatel**

### CODE REVIEW

**Comment by silee2** [comment]
Update test cases after changes made by #702

**Comment by adstraw** [comment]
Scott is in meetings all day.  You might add @yxlao who made the original change instead.

**Comment by adstraw** [comment]
Do we need to wait on @baojun-nervana ?

**Comment by nbpatel** [comment]
He was the one who wrote the tests hence i added him. But I think we should be ok with two approvals

**Comment by adstraw** [comment]
I would prefer to see all reviewers +1 but given these tests are broken I plan to merge this when it passes CI.

**Pull request merged**
