### PR TITLE
Make temp memory pools static to avoid memory allocation overheads

### PR DESCRIPTION
**Pull request by jbobba**

### CODE REVIEW

**Comment by rkimballn1** [comment]
TESTNOW

**Comment by jbobba** [comment]
This was one of the reasons we had to do a custom MKL allocator in TF. Should have caught it earlier. Hoping it doesn't introduce a leak though.

**Comment by jbobba** [comment]
TESTNOW

**Comment by jbobba** [comment]
TESTNOW

**Pull request merged**
