### PR TITLE
[ONNX] Non-linear ops

### PR DESCRIPTION
**Pull request by tsocha**

### CODE REVIEW

**Comment by tsocha** [comment]
TEST NOW

**Comment by tsocha** [comment]
TEST NOW

**Comment by tsocha** [comment]
TEST NOW

**Comment by tsocha** [comment]
TEST NOW

**Comment by arogowie-intel** [comment]
TEST NOW

**Comment by postrational** [comment]
TEST NOW

**Comment by postrational** [comment]
Please merge after:
https://github.com/NervanaSystems/ngraph-onnx/pull/218

**Pull request merged**
