### PR TITLE
Normalize the printing of settings of bools to ON/OFF

### PR DESCRIPTION
**Pull request by rkimballn1**
Now we get this. All bools are normalized to TRUE or FALSE so no more mixture of ON/OFF
```
-- NGRAPH_UNIT_TEST_ENABLE:        ON
-- NGRAPH_TOOLS_ENABLE:            ON
-- NGRAPH_CPU_ENABLE:              OFF
-- NGRAPH_INTELGPU_ENABLE:         OFF
-- NGRAPH_GPU_ENABLE:              OFF
-- NGRAPH_INTERPRETER_ENABLE:      ON
-- NGRAPH_NOP_ENABLE:              ON
-- NGRAPH_GPUH_ENABLE:             OFF
-- NGRAPH_GENERIC_CPU_ENABLE:      OFF
-- NGRAPH_DISTRIBUTED_MLSL_ENABLE: OFF
-- NGRAPH_DISTRIBUTED_OMPI_ENABLE: OFF
-- NGRAPH_DEBUG_ENABLE:            OFF
-- NGRAPH_ONNX_IMPORT_ENABLE:      OFF
-- NGRAPH_DEX_ONLY:                OFF
-- NGRAPH_CODE_COVERAGE_ENABLE:    OFF
-- NGRAPH_LIB_VERSIONING_ENABLE:   OFF
-- NGRAPH_PYTHON_BUILD_ENABLE:     OFF
-- NGRAPH_USE_PREBUILT_LLVM:       ON
-- NGRAPH_PLAIDML_ENABLE:          OFF
```

### CODE REVIEW

**Comment by rkimballn1** [comment]
Do we want TRUE/FALSE or ON/OFF? It is trivial to change.

**Comment by silee2** [comment]
I think ON/OFF is the norm. Not sure why we ended up with a lot of TRUE/FALSE.

**Comment by diyessi** [comment]
Would it make sense to be consistent on `ENABLE`, i.e. `NGRAPH_DEX_ENABLE` and `NGRAPH_CODEGEN_ENABLE` and `NGRAPH_PREBUILT_LLVM_ENABLE` ?
Upon looking at the list, isn't `NGRAPH_ENABLE_X` more common than `NGRAPH_X_ENABLE`?

**Comment by rkimballn1** [comment]
I have never liked the DEX_ONLY flag. It does not make sense. It would be much more clear if the CPU backend were really two proper and separate CPU backends, the interpreted version and the compiled version. Two backends with two names.
I also don't like the distributed flags NGRAPH_DISTRIBUTED_MLSL_ENABLE and NGRAPH_DISTRIBUTED_OMPI_ENABLE and would much prefer NGRAPH_DISBRIBUTED_ENABLE to be one of OFF/OMPI/MLSL as a single option. Two options allows for the state where both MLSL and OMPI are requested which is an error.
All of this is at least one more separate PR.

**Comment by diyessi** [comment]
`NGRAPH_DISTRIBUTED_ENABLE` as on/off
`NGRAPH_DISTRIBUTED_KIND` as MLSL, OMPI, etc. with an error if one is not supplied when enabled.

**Comment by rkimballn1** [comment]
And a new backend, something like CODEGENCPU or CCPU with CPU being the DEX version of the CPU backend.

**Pull request merged**
