### PR TITLE
[Py] Enable ngraph-cpp ops in Python API

### PR DESCRIPTION
**Pull request by tsocha**
- Batch normalization
- Function call
- Get output element

### CODE REVIEW

**Comment by tsocha** [comment]
TESTNOW

**Comment by tsocha** [comment]
TESTNOW

**Comment by Krovatkin** [comment]
TESTNOW

**Comment by Krovatkin** [comment]
@DawnStone I'm completely confuzzled by the failing CI. This PR doesn't make any changes that could possibly affect our cpp unit tests aside from maybe breaking the code style validation which doesn't seem to be the case here. I was wondering if you could help me to tell what went wrong here?

**Comment by Krovatkin** [comment]
TESTNOW

**Comment by DawnStone** [comment]
TESTNOW

**Comment by DawnStone** [comment]
TESTNOW

**Pull request merged**
