### PR TITLE
[ ONNX IMPORTER ] Flatten with axis==1 simplification

### PR DESCRIPTION
**Pull request by jane-intel**

### CODE REVIEW

**Comment by tomdol** [comment]
Can we also do the same for the master branch?

**Comment by jane-intel** [comment]
> Can we also do the same for the master branch?

@tomdol sure, but I see that it is not merged yet

**Comment by tomdol** [comment]
> > Can we also do the same for the master branch?
> 
> @tomdol sure, but I see that it is not merged yet

You can start a separate PR from the same branch `importer/evgenya/flatten`  but this time to master. They can be open in parallel.

**Comment by mitruska** [comment]
> > > Can we also do the same for the master branch?
> > 
> > 
> > @tomdol sure, but I see that it is not merged yet
> 
> You can start a separate PR from the same branch `importer/evgenya/flatten` but this time to master. They can be open in parallel.

Thank you, of course I can merge this PR to the `onnx/enable_mask_rcnn` branch
but to the `master` I think we can simply include this change in PR [#4488](https://github.com/NervanaSystems/ngraph/pull/4488) because it's still open.

**Pull request merged**
