### PR TITLE
Add Inference Engine (IE) backend

### PR DESCRIPTION
**Pull request by adstraw**
IE backend framework = a slimmed down version of the interpreter backend.  Calls to inference engine graph API will replace calls to reference kernels over time.

### CODE REVIEW

**Comment by adstraw** [comment]
TESTNOW

**Comment by RanACohen** [comment]
sorry for the late reply.

I'll check it out on Sunday.

**Comment by adstraw** [comment]
TESTNOW

**Comment by adstraw** [comment]
TESTNOW

**Comment by rkimballn1** [comment]
TESTNOW

**Pull request merged**
