### PR TITLE
CI checks dynamic -> master

### PR DESCRIPTION
**Pull request by tomdol**
This PR was opened just to run the CI on both ends (ng & ov)

### CODE REVIEW

**Comment by tomdol** [comment]
The CI fails with the following error:
```
[2020-05-07T11:20:34.985Z] CMake Error at ngraph/src/ngraph/runtime/ie/CMakeLists.txt:33 (find_package):
[2020-05-07T11:20:34.985Z]   By not providing "FindInferenceEngine.cmake" in CMAKE_MODULE_PATH this
[2020-05-07T11:20:34.985Z]   project has asked CMake to find a package configuration file provided by
[2020-05-07T11:20:34.985Z]   "InferenceEngine", but CMake did not find one.
[2020-05-07T11:20:34.985Z] 
[2020-05-07T11:20:34.985Z]   Could not find a package configuration file provided by "InferenceEngine"
[2020-05-07T11:20:34.985Z]   with any of the following names:
[2020-05-07T11:20:34.985Z] 
[2020-05-07T11:20:34.985Z]     InferenceEngineConfig.cmake
[2020-05-07T11:20:34.985Z]     inferenceengine-config.cmake
```

https://gitlab-icv.inn.intel.com/inference-engine/dldt/merge_requests/7424

I suspect that this PR introduced the build break https://github.com/NervanaSystems/ngraph/pull/4627

**Comment by tomdol** [comment]
The build break to be reverted by https://github.com/NervanaSystems/ngraph/pull/4694 in the dynamic branch

**Comment by rkimballn1** [comment]
You need to select a hash on dynamic to test with. The dynamic branch is constantly being modified by PR merging

**Comment by rkimballn1** [comment]
Only Ashok should merge to master

**Pull request closed without merging**
