### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by postrational**
This is a proposal to enable Travis for public-facing CI of ngraph.

### CODE REVIEW

**Comment by jennifermyers** [comment]
LGTM

**Comment by diyessi** [comment]
Are we duplicating docker setups we have other places?

**Comment by postrational** [comment]
The current setup actually runs tests on both Python 2 and 3.

Python 2: https://travis-ci.org/NervanaSystems/ngraph/jobs/362110086#L6406-L6423
Python 3: https://travis-ci.org/NervanaSystems/ngraph/jobs/362110086#L7413-L7430

**Comment by postrational** [comment]
I did notice a different potential problem however.
Our build and testing takes about 41 minutes. 
This is dangerously close to the 50 minute timeout set for a job. 

We may need to split the build into multiple jobs to avoid timeouts.

**Comment by postrational** [comment]
Added a way to run tests in parallel, this should avoid the 50 minute timeout.

**Pull request merged**
