### PR TITLE
Modify slice layout.

### PR DESCRIPTION
**Pull request by ayzhuang**
Fix a bug in horizontal fusion.

### CODE REVIEW

**Comment by postrational** [comment]
TEST NOW

**Comment by postrational** [comment]
TEST NOW

**Comment by jbobba** [comment]
TEST NOW

**Comment by arogowie-intel** [comment]
TEST NOW

**Comment by jbobba** [comment]
TEST NOW

**Comment by rkimballn1** [comment]
TEST NOW used to be TESTNOW and it used to work. 
Currently TESTNOW does not work on the ngraph repo so typing it does nothing other than add a comment.

**Comment by jbobba** [comment]
ok. i know you mentioned that you had sent out a note about this but i wasn't able to track it down. Not sure how ONNX got started but it passes. We are good for now.

**Comment by rkimballn1** [comment]
Yea, I pinned it in slack on #ngraph but you will probably never find it. Chris is going to put a how-to page on how to do it

**Pull request merged**
