### PR TITLE
Accept version label from cmake command line

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by earhart** [comment]
When building from my clone:

```
$ cmake .. -DNGRAPH_CPU_ENABLE=false -DNGRAPH_PLAIDML_ENABLE=true -DPlaidML_DIR=/Users/rearhart/plaidml -DNGRAPH_INSTALL_PREFIX=/Users/rearhart/ngraph_dist
-- Found Git: /usr/local/bin/git (found version "2.19.0")
From git@github.com:vertexai/ngraph.git
CMake Error at cmake/Modules/git_tags.cmake:39 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  cmake/Modules/git_tags.cmake:60 (NGRAPH_GET_TAG_OF_CURRENT_HASH)
  CMakeLists.txt:22 (NGRAPH_GET_VERSION_LABEL)


CMake Error at CMakeLists.txt:29 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:30 (list):
  list GET given empty list


CMake Error at CMakeLists.txt:31 (list):
  list GET given empty list


-- NGRAPH_VERSION
-- NGRAPH_VERSION_SHORT
-- NGRAPH_API_VERSION
```
It'd be nice to be able to fork and build.

**Comment by rkimballn1** [comment]
I just did a fork of ngraph using my personal account
https://github.com/rkimball/ngraph
and when I build I see this
```
(venv2) [rkimball@rhkimbal-MOBL2 build]$ cmake .. -DNGRAPH_CPU_ENABLE=FALSE
-- Found Git: /usr/bin/git (found version "2.7.4")
From https://github.com/rkimball/ngraph.git
-- NGRAPH_VERSION 0.9.0-rc.3+4552d02
-- NGRAPH_VERSION_SHORT 0.9.0
-- NGRAPH_API_VERSION 0.9
```

**Comment by rkimballn1** [comment]
Looking at your fork https://github.com/vertexai/ngraph I don't see any tags. When I forked my test branch I used the `fork` button on the ngraph github website. How was your fork forked? 
Somehow on your repo it was either forked without tags or tags were removed. The version is determinted from the tags so they can't be removed.

**Comment by earhart** [comment]
I didn't do a GitHub fork; I pulled the canonical nGraph repo, and then pushed to vertexai/ngraph just to stash my changes somewhere.

**Pull request closed without merging**
