### PR TITLE
CMAKE: export ngraph target to build tree NGraphConfig.cmake

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
export ngraph target to build tree NGraphConfig.cmake to be able to link outside

CC @ilyachur

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@silee2, please, review.

**Comment by ilya-lavrenov** [comment]
@aslepko, please, review.

**Comment by ilya-lavrenov** [comment]
ping

**Comment by ilyachur** [comment]
Looks like [this PR](https://github.com/NervanaSystems/ngraph/pull/3790) solves the same issue for more generic case.

**Pull request closed without merging**
