### PR TITLE
remove version tagging from shared libraries

### PR DESCRIPTION
**Pull request by rkimballn1**

### CODE REVIEW

**Comment by ransford2011** [comment]
@rkimballn1. Can we please guard this by a variable as this is needed for my release efforts. Thanks!

**Comment by avijit-nervana** [comment]
@ransford2011 Yes - I agree. This could be guarded by a cmake flag. The requested behavior would be: When this cmake flag is specified, the libraries will have the version numbers.

**Comment by rkimballn1** [comment]
TESTNOW

**Comment by diyessi** [comment]
Blocked while constant folding issue is investigated.

**Pull request merged**
