### PR TITLE
Add CUDNN_SAFE_CALL and CUBLAS_SAFE_CALL

### PR DESCRIPTION
**Pull request by fengleitian**
Those two macro will catch the cudnn and cublas running error.

### CODE REVIEW

**Comment by fengleitian** [comment]
@csullivan is it the latest version? It runs without problem here.

**Comment by rkimballn1** [comment]
TESTNOW

**Comment by rkimballn1** [comment]
TESTNOW

**Comment by rkimballn1** [comment]
TESTNOW

**Pull request merged**
