### PR TITLE
Modified CUDNN headers throughout nGraph: cudnn_v7.h -> cudnn.h.

### PR DESCRIPTION
**Pull request by csullivan**
This better supports non-ubuntu/debian systems.

Addresses issue #864.

### CODE REVIEW

**Comment by csullivan** [comment]
TESTNOW

**Comment by csullivan** [comment]
Seems there is a bad GPG signature on cudatools from nvidia.com at the moment and so CI is failing to spin up the GPU docker. 
```
[Build_And_Test_GPU_clang_ubuntu1604_gpu] W: GPG error: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release: The following signatures were invalid: BADSIG F60F4B3D7FA2AF80 cudatools <cudatools@nvidia.com>
[Build_And_Test_GPU_clang_ubuntu1604_gpu] W: The repository 'http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release' is not signed.
[Build_And_Test_GPU_clang_ubuntu1604_gpu] E: Failed to fetch store:/var/lib/apt/lists/partial/developer.download.nvidia.com_compute_machine-learning_repos_ubuntu1604_x86%5f64_Packages.gz  Hash Sum mismatch
[Build_And_Test_GPU_clang_ubuntu1604_gpu] E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Rerunning CI again to test if anything has changed on the nvidia end.

**Comment by csullivan** [comment]
TESTNOW

**Comment by csullivan** [comment]
This time around we are getting a slightly different error about a mismatched hash:
```
[Build_And_Test_GPU_clang_ubuntu1604_gpu] E: Failed to fetch store:/var/lib/apt/lists/partial/developer.download.nvidia.com_compute_machine-learning_repos_ubuntu1604_x86%5f64_Packages.gz  Hash Sum mismatch
[Build_And_Test_GPU_clang_ubuntu1604_gpu] E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by fengleitian** [comment]
There was some problem before, @DawnStone use the link as a workaround. My understanding is it's different from system to system. I haven't dig into it. cudnn.h works on some system and cudnn_v7 works on some others.

**Comment by csullivan** [comment]
TESTNOW

**Comment by csullivan** [comment]
@fengleitian, @diyessi, @rkimballn1 it appears that the nvidia hash issue is now resolved, please review.

**Comment by csullivan** [comment]
@fengleitian, as far as I can tell the link 
`/usr/include/cudnn.h -> /etc/alternatives/libcudnn -> /usr/include/x86_64-linux-gnu/cudnn_v7.h` is generated on ubuntu/debian systems, for example see https://github.com/tensorflow/tensorflow/issues/6850.

**Comment by fengleitian** [comment]
Thanks @csullivan. Thanks @WilliamTambellini for checking

**Comment by rsketine** [comment]
[ RUN      ] CPU.one_hot_scalar_fp_nonint_in_3
[       OK ] CPU.one_hot_scalar_fp_nonint_in_3 (433 ms)
[ RUN      ] CPU.one_hot_scalar_oob_in_3
terminate called after throwing an instance of 'std::range_error'
  what():  One-hot: value is out of category range
[bfe283b8fa0e:06779] *** Process received signal ***
[bfe283b8fa0e:06779] Signal: Aborted (6)
[bfe283b8fa0e:06779] Signal code:  (-6)
[bfe283b8fa0e:06779] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fea49f41390]
[bfe283b8fa0e:06779] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fea490f6428]
[bfe283b8fa0e:06779] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fea490f802a]
[bfe283b8fa0e:06779] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d)[0x7fea49a3984d]
[bfe283b8fa0e:06779] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d6b6)[0x7fea49a376b6]
[bfe283b8fa0e:06779] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d701)[0x7fea49a37701]
[bfe283b8fa0e:06779] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d919)[0x7fea49a37919]
[bfe283b8fa0e:06779] [ 7] [0x7fea29e53665]
[bfe283b8fa0e:06779] *** End of error message ***
Aborted (core dumped)
test/CMakeFiles/unit-test-check.dir/build.make:57: recipe for target 'test/CMakeFiles/unit-test-check' failed
make[3]: *** [test/CMakeFiles/unit-test-check] Error 134
make[3]: Leaving directory '/home/dockuser/ngraph/BUILD-GCC'
CMakeFiles/Makefile2:740: recipe for target 'test/CMakeFiles/unit-test-check.dir/all' failed
make[2]: *** [test/CMakeFiles/unit-test-check.dir/all] Error 2
make[2]: Leaving directory '/home/dockuser/ngraph/BUILD-GCC'
CMakeFiles/Makefile2:747: recipe for target 'test/CMakeFiles/unit-test-check.dir/rule' failed
make[1]: *** [test/CMakeFiles/unit-test-check.dir/rule] Error 2
make[1]: Leaving directory '/home/dockuser/ngraph/BUILD-GCC'
Makefile:331: recipe for target 'unit-test-check' failed
make: *** [unit-test-check] Error 2

Check this log for the full failure: https://aipg-rancher.intel.com/jenkins/algo/view/ngraph-cpp-merge-integration-Results/job/ngraph-unittest/3591/artifact/docker-run-build-and-test_CPU_distributed_gcc_ubuntu1604_openmpi.log

**Comment by csullivan** [comment]
@rsketine, this smells like another CI issue as this PR changes only a single header name which is GPU related and should not impact the CPU tests which are what is failing..

**Pull request merged**
