### PR TITLE
Backend test: MaxPoolBackprop test strided and padded

### PR DESCRIPTION
**Pull request by shssf**
**WARNING**
This test passes with `INTERPRETER`, `INTELGPU` and `GPU` backends but failed with `CPU` backend.

Should I add `unit_test.manifest` file changes for CPU backend in this case?

This PR is related to PR #1427 because test system has no test for MaxPoolBackprop operation with padding

### CODE REVIEW

**Comment by rkimballn1** [comment]
We can't merge if it is failing on the CPU backend. We should add this test to the CPU backend's manifest file and let @jbobba know that the test is failing.

**Comment by shssf** [comment]
@rkimballn1 Yes, I just asked for possible way to go further. I will add this to manifest shortly. Thank you.

**Comment by jbobba** [comment]
Can you check if the test is still failing? I checked on your branch. Seems to pass on CPU. 

$> ~/repos/private-ngraph-cpp/builds$ test/unit-test --gtest_filter="CPU.backwards_maxpool_n2_c1_hw5*"
Note: Google Test filter = CPU.backwards_maxpool_n2_c1_hw5*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CPU
[ RUN      ] CPU.backwards_maxpool_n2_c1_hw5_3x3_str2_max
[       OK ] CPU.backwards_maxpool_n2_c1_hw5_3x3_str2_max (3215 ms)
[----------] 1 test from CPU (3215 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3215 ms total)
[  PASSED  ] 1 test.
$>~/repos/private-ngraph-cpp/builds$ git branch
* intelgpu_backend_max_pool_backprop_operation_test

**Comment by jbobba** [comment]
Ok. We will look into after it is merged in.

**Pull request merged**
