### PR TITLE
Update bezel version

### PR DESCRIPTION
**Pull request by lwencel**
TensorFlow 1.7 will not compile with bezel 0.5.4.
The minimum version of bazel is 0.10.0, but I recommend using version 0.11.1.

### CODE REVIEW

**Comment by avijit-nervana** [comment]
We should make this change as the version of TF we have open sourced is 1.3 based which won't work with 0.11.

**Comment by lwencel** [comment]
@avijit-nervana ok, I was not sure that you are using TF 1.3, because in documentation you recommand to use `git clone git@github.com:NervanaSystems/ngraph-tensorflow.git`. This will clone private repository with TensorFlow 1.7 which requires bazel 0.10.0 (point 5 in http://ngraph.nervanasys.com/docs/latest/framework-integration-guides.html#tensorflow-intg)
Should I use `https://github.com/NervanaSystems/ngraph-tensorflow-1.3` instead of `git@github.com:NervanaSystems/ngraph-tensorflow.git`?

**Comment by avijit-nervana** [comment]
@lwencel Yes - please clone the 1.3 branch. @indie Could you please fix the documentation? Thanks.

**Comment by adstraw** [comment]
is this PR dead?  can we close it>  @avijit-nervana @lwencel

**Comment by avijit-nervana** [comment]
We need to update the documentation - so once that is done we should close this.

**Comment by adstraw** [comment]
Closing this PR per @avijit-nervana, fixed in #726

**Pull request closed without merging**
