### PR TITLE
Move to MKLDNN v0.16. Git hash picks up some bug fixes post v0.16

### PR DESCRIPTION
**Pull request by jbobba**

### CODE REVIEW

**Comment by jbobba** [comment]
@avijit-nervana haven't seen them do minor versioning.

**Comment by jbobba** [comment]
https://jira01.devtools.intel.com/projects/MFDNN/issues/MFDNN-982

**Comment by avijit-nervana** [comment]
@jbobba Can't view the comments in the JIRA link above - access denied

**Comment by jbobba** [comment]
@rsketine tests pass now.

**Comment by rsketine** [comment]
running the other configs once done will approve
https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-build-env-test/

**Comment by rsketine** [comment]
https://aipg-rancher.intel.com/jenkins/algo/job/ngraph-build-env-test/1178/artifact/docker-run-build-and-test_CPU_gcc48_centos74_gcc48.log (Some issue here but it was there before need to debug this. Nothing to do with this change.)

**Pull request merged**
